# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - none

# Specifies the type of runner that the pipeline will run on.
pool:
  name: Default

steps:

# Configures your Maven project.  
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    goals: 'tia:affected-tests test -Djtest.report=report -Djtest.referenceCoverageFile=C:\home\various\jenkins\parabank_ut_reports\coverage.xml -Djtest.referenceReportFile=C:\home\various\jenkins\parabank_ut_reports\report.xml'
    