version: '3'
services:
  selenic:
    image: pteodor/selenic:4.0
    container_name: selenic
    environment:
      - UID=995
      - GID=991
    networks:
      - mynetwork
    volumes:
      - /var/lib/jenkins/workspace/Testing Jobs/Parabank-Jenkins (Pawel-Selenic main branch)/parabank-jenkins:/home/parasoft/jenkins/parabank-jenkins
      - /var/lib/jenkins/workspace/Testing Jobs/Parabank-Jenkins (Pawel-Selenic main branch)/parabank-selenic:/home/parasoft/jenkins/parabank-selenic
    working_dir: /home/parasoft/jenkins/parabank-selenic
    #entrypoint: ["mvn", "test"]
    command: >
      sh -c "/usr/local/tomcat/bin/startup.sh && mvn test"
    stdin_open: true 
    tty: true
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    environment:
      - UID=995
      - GID=991
    networks:
      - mynetwork
networks:
  mynetwork:       
