version: '3'
services:
  selenic:
    user: 995:991
    image: pteodor/selenic:7.0
    container_name: selenic
    networks:
      - demo-net
    volumes:
      - /var/lib/jenkins/workspace/Testing Jobs/Parabank-Jenkins (Pawel-Selenic main)/parabank-jenkins:/home/parasoft/jenkins/parabank-jenkins
      - /var/lib/jenkins/workspace/Testing Jobs/Parabank-Jenkins (Pawel-Selenic main)/parabank:/home/parasoft/jenkins/parabank
    working_dir: /home/parasoft/jenkins/parabank
    #entrypoint: ["mvn", "test"]
    command: >
      sh -c "cp /home/parasoft/jenkins/parabank-jenkins/selenic.properties /selenic && mvn test -DargLine=-javaagent:/selenic/selenic_agent.jar=captureDom=true"
    stdin_open: true 
    tty: true
  selenium-chrome:
    user: 995:991
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    networks:
      - demo-net
networks:
  demo-net:  
    external: true     
